name: Test convert 2048 GUI

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Raylib and Run Makefile
      run: sudo apt install libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev; make;
    
    - name: Upload GUI Executable
      if: ${{ always() }}

      uses: actions/upload-artifact@v4
      with:
        name: GUI Executable
        path: ./main